; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "OxyPlayer"
#define MyAppVersion "0.95.25.08.17"
#define MyAppPublisher "haoluan"
#define MyAppURL "https://gitee.com/haoluan_bilibili/oxy-player"
#define MyAppExeName "OxyPlayer.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{4CF19DEA-5C91-4563-98C3-89B31498E435}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
DefaultGroupName={#MyAppName}
LicenseFile=D:\VS_Project\OxyPlayer\LICENSE.rtf
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=D:\iss_Out
OutputBaseFilename=Oxyplayer
SolidCompression=yes
WizardStyle=modern

; 添加.NET Framework 4.7.2检查
[Code]
function IsDotNet472OrNewer: Boolean;
var
  Release: Cardinal;
begin
  // 检查注册表键值
  if RegQueryDWordValue(
       HKLM, 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', 'Release', Release) then
  begin
    // Release >= 461808 表示 .NET Framework 4.7.2 或更高版本
    Result := (Release >= 461808);
  end
  else
  begin
    Result := False;
  end;
end;

function InitializeSetup: Boolean;
var
      ErrorCode: Integer;
begin
  // 检查.NET Framework
  if not IsDotNet472OrNewer then
  begin
    if MsgBox(
         '{#MyAppName} {#MyAppVersion} 需要 Microsoft .NET Framework 4.7.2 Runtime 或更高版本。' + #13#10 +
         '是否立即打开 Microsoft 官网下载页面？',
         mbConfirmation, MB_YESNO) = IDYES then    
    begin
      // 打开.NET Framework下载页面
      ShellExec('open',
        'https://dotnet.microsoft.com/download/dotnet-framework/net472',
        '', '', SW_SHOW, ewNoWait,ErrorCode);
    end
    else
    begin
        // Display a message box
      if SuppressibleTaskDialogMsgBox('Warning', '警告！{#MyAppName} {#MyAppVersion} 需要 .NET Framework 4.7.2 才能正常运行，如果存在安装程序检测错误，请单击"强制安装"按钮来继续安装', mbError, MB_OKCANCEL, ['强制安装（无视.NET环境检测）'], 0, IDOK) = IDOK then
      begin
        Result := True; 
        // user clicked OK
      end;
    end;
    Result := False;  // 中止安装
  end
  else
  begin
    // Display a message box
    Result := True;  // 继续安装
  end;
end;

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\Chinese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\VS_Project\OxyPlayer\OxyPlayer\bin\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VS_Project\OxyPlayer\OxyPlayer\bin\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\MusicTag"; Filename: "{app}\MusicTag\MusicTag.exe"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

