//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OxyPlayer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class OxySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static OxySettings defaultInstance = ((OxySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OxySettings())));
        
        public static OxySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FileCount {
            get {
                return ((int)(this["FileCount"]));
            }
            set {
                this["FileCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体, 18pt")]
        public global::System.Drawing.Font DesktopLyricsFont {
            get {
                return ((global::System.Drawing.Font)(this["DesktopLyricsFont"]));
            }
            set {
                this["DesktopLyricsFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color DesktopLyricsColor {
            get {
                return ((global::System.Drawing.Color)(this["DesktopLyricsColor"]));
            }
            set {
                this["DesktopLyricsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double Opacity {
            get {
                return ((double)(this["Opacity"]));
            }
            set {
                this["Opacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShownDesklopLyrics {
            get {
                return ((bool)(this["ShownDesklopLyrics"]));
            }
            set {
                this["ShownDesklopLyrics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockDesktopLyrics {
            get {
                return ((bool)(this["LockDesktopLyrics"]));
            }
            set {
                this["LockDesktopLyrics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DesktopLyricsLocation {
            get {
                return ((global::System.Drawing.Point)(this["DesktopLyricsLocation"]));
            }
            set {
                this["DesktopLyricsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MusicFolderPath {
            get {
                return ((string)(this["MusicFolderPath"]));
            }
            set {
                this["MusicFolderPath"] = value;
            }
        }
    }
}
