//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OxyPlayer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.6.0.0")]
    public sealed partial class Palette : global::System.Configuration.ApplicationSettingsBase {
        
        private static Palette defaultInstance = ((Palette)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Palette())));
        
        public static Palette Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80, 160, 255")]
        public global::System.Drawing.Color ActivedColor {
            get {
                return ((global::System.Drawing.Color)(this["ActivedColor"]));
            }
            set {
                this["ActivedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightCyan")]
        public global::System.Drawing.Color ControlerBackgroudColor {
            get {
                return ((global::System.Drawing.Color)(this["ControlerBackgroudColor"]));
            }
            set {
                this["ControlerBackgroudColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color PlaylistBackgroudColor {
            get {
                return ((global::System.Drawing.Color)(this["PlaylistBackgroudColor"]));
            }
            set {
                this["PlaylistBackgroudColor"] = value;
            }
        }
    }
}
